// Guide Mode — deterministic angle/POV presets
// No LLM involved. These tags are appended directly to the anchor prompt.

export type GuideTab = 'camera' | 'framing' | 'pov' | 'intimate';

export interface GuideAngle {
  id: string;
  label: string;
  emoji: string;
  /** The prompt delta string appended after the anchor prompt */
  tag: string;
  tab: GuideTab;
}

export const GUIDE_TABS: { id: GuideTab; label: string; emoji: string }[] = [
  { id: 'camera',   label: 'Camera',   emoji: '📷' },
  { id: 'framing',  label: 'Framing',  emoji: '🎞️' },
  { id: 'pov',      label: 'POV',      emoji: '👁️' },
  { id: 'intimate', label: 'Intimate', emoji: '🔥' },
];

export const GUIDE_ANGLES: GuideAngle[] = [
  // ── 📷 Camera (vertical & horizontal axis) ──────────────────────────────
  {
    id: 'eye_level',
    label: 'Eye Level',
    emoji: '👀',
    tag: 'eye level, neutral camera height, straight on',
    tab: 'camera',
  },
  {
    id: 'slight_low',
    label: 'Slight Low',
    emoji: '⬇️',
    tag: 'slight low angle, camera just below eye level',
    tab: 'camera',
  },
  {
    id: 'low_angle',
    label: 'Low Angle',
    emoji: '📐',
    tag: 'low angle shot, looking up at subject, camera placed below',
    tab: 'camera',
  },
  {
    id: 'worms_eye',
    label: "Worm's-Eye",
    emoji: '🐛',
    tag: "worm's-eye view, floor POV, camera on ground looking up, extreme low angle",
    tab: 'camera',
  },
  {
    id: 'slight_high',
    label: 'Slight High',
    emoji: '⬆️',
    tag: 'slight high angle, camera just above eye level, looking slightly down',
    tab: 'camera',
  },
  {
    id: 'high_angle',
    label: 'High Angle',
    emoji: '🔭',
    tag: 'high angle shot, looking down at subject, camera placed above',
    tab: 'camera',
  },
  {
    id: 'overhead',
    label: 'Overhead',
    emoji: '🛸',
    tag: 'overhead shot, top-down view, camera directly above subject',
    tab: 'camera',
  },
  {
    id: 'birds_eye',
    label: "Bird's-Eye",
    emoji: '🦅',
    tag: "bird's-eye view, top-down view, directly above subject, 90 degree angle",
    tab: 'camera',
  },
  {
    id: 'dutch',
    label: 'Dutch Angle',
    emoji: '↗️',
    tag: 'dutch angle, canted framing, tilted camera, 45-degree rotation',
    tab: 'camera',
  },
  {
    id: 'front',
    label: 'Frontal',
    emoji: '⬜',
    tag: 'frontal view, straight on, head-on, facing camera directly, perfect symmetry',
    tab: 'camera',
  },
  {
    id: 'three_quarter',
    label: '3/4 Profile',
    emoji: '↩️',
    tag: 'dynamic 3/4 profile, three-quarter view of face, head turned slightly',
    tab: 'camera',
  },
  {
    id: 'full_profile',
    label: 'Side Profile',
    emoji: '👤',
    tag: 'full profile shot, side view, strict 90-degree angle, sharp jawline, profile silhouette',
    tab: 'camera',
  },
  {
    id: 'from_behind',
    label: 'From Behind',
    emoji: '🔙',
    tag: 'shot from behind, rear angle, back view, subject facing away from camera',
    tab: 'camera',
  },
  {
    id: 'looking_back',
    label: 'Looking Back',
    emoji: '👀',
    tag: 'standing, looking back over shoulder, rear three-quarter view',
    tab: 'camera',
  },

  // ── 🎞️ Framing (shot size / crop) ────────────────────────────────────────
  {
    id: 'ecl',
    label: 'Extreme Close-Up',
    emoji: '🔬',
    tag: 'extreme close-up, macro photography, tight crop, hyper-detailed',
    tab: 'framing',
  },
  {
    id: 'close_up',
    label: 'Close-Up',
    emoji: '🤳',
    tag: 'close-up shot, portrait headshot, framing head and neck, 85mm lens',
    tab: 'framing',
  },
  {
    id: 'bust',
    label: 'Bust Shot',
    emoji: '👗',
    tag: 'medium close-up, bust shot, framed from chest up, head and shoulders',
    tab: 'framing',
  },
  {
    id: 'chest_up',
    label: 'Chest-Up',
    emoji: '👔',
    tag: 'chest up shot, upper torso framing, breast line and above',
    tab: 'framing',
  },
  {
    id: 'waist_up',
    label: 'Waist-Up',
    emoji: '⬛',
    tag: 'medium shot, waist up, framed from waist up, half-body',
    tab: 'framing',
  },
  {
    id: 'hip_up',
    label: 'Hip-Up',
    emoji: '📏',
    tag: 'hip up shot, framed from hips and above',
    tab: 'framing',
  },
  {
    id: 'cowboy',
    label: 'Cowboy Shot',
    emoji: '🤠',
    tag: 'cowboy shot, mid-thigh up, framing hips and torso, confident stance',
    tab: 'framing',
  },
  {
    id: 'full_body',
    label: 'Full Body',
    emoji: '🧍',
    tag: 'full body shot, head to toe, full character framing, full length standing',
    tab: 'framing',
  },
  {
    id: 'torso_crop',
    label: 'Torso Crop',
    emoji: '✂️',
    tag: 'torso only, no head, no legs, extreme close-up, abstract body crop, chest to hip',
    tab: 'framing',
  },
  {
    id: 'lower_body',
    label: 'Lower Body',
    emoji: '🦵',
    tag: 'lower body shot, hips to feet, legs framing',
    tab: 'framing',
  },
  {
    id: 'legs_only',
    label: 'Legs Only',
    emoji: '🦿',
    tag: 'legs only, thighs to feet, full leg length in frame',
    tab: 'framing',
  },
  {
    id: 'decollete',
    label: 'Décolleté',
    emoji: '💎',
    tag: 'decolletage close-up, chest detail shot, medium close-up, bust framing',
    tab: 'framing',
  },
  {
    id: 'back_crop',
    label: 'Back Crop',
    emoji: '🔄',
    tag: 'back shot, shoulder to lower back, rear torso crop',
    tab: 'framing',
  },
  {
    id: 'silhouette',
    label: 'Silhouette',
    emoji: '🌅',
    tag: 'silhouette, backlit window, full body, dark subject outline, high contrast, rim lighting',
    tab: 'framing',
  },

  // ── 👁️ POV (point of view / perspective) ─────────────────────────────────
  {
    id: 'selfie',
    label: 'Selfie POV',
    emoji: '🤳',
    tag: 'selfie angle, handheld pov, slightly above eye level, close-up, direct eye contact',
    tab: 'pov',
  },
  {
    id: 'mirror_selfie',
    label: 'Mirror Selfie',
    emoji: '🪞',
    tag: 'mirror selfie, holding smartphone, casual mirror reflection, full body',
    tab: 'pov',
  },
  {
    id: 'mirror_pov',
    label: 'Mirror Reflection',
    emoji: '🔮',
    tag: 'mirror reflection, shooting into mirror, double perspective, boudoir scene',
    tab: 'pov',
  },
  {
    id: 'ots',
    label: 'Over-the-Shoulder',
    emoji: '🫧',
    tag: 'over-the-shoulder shot, looking past foreground figure, shallow depth of field',
    tab: 'pov',
  },
  {
    id: 'voyeur_door',
    label: 'Doorway Voyeur',
    emoji: '🚪',
    tag: 'framed through doorway, voyeur angle, foreground door frame, shallow depth of field, subject in background',
    tab: 'pov',
  },
  {
    id: 'voyeur_curtain',
    label: 'Through Curtain',
    emoji: '🪟',
    tag: 'soft foreground curtain blur, through sheer fabric, voyeur angle, window light',
    tab: 'pov',
  },
  {
    id: 'peephole',
    label: 'Peephole',
    emoji: '🔵',
    tag: 'fisheye lens, peephole perspective, circular vignette, extreme wide angle, voyeur effect',
    tab: 'pov',
  },
  {
    id: 'first_person',
    label: 'First-Person',
    emoji: '🎮',
    tag: 'first-person POV, shot from viewer perspective, immersive, pov',
    tab: 'pov',
  },
  {
    id: 'window',
    label: 'Through Window',
    emoji: '🏠',
    tag: 'through window, looking in, exterior perspective, window frame, voyeur',
    tab: 'pov',
  },
  {
    id: 'self_gaze',
    label: 'Self-Gaze',
    emoji: '⬇️',
    tag: 'pov, self-gaze, looking down at own body, chest-up view from above, subjective camera',
    tab: 'pov',
  },

  // ── 🔥 Intimate (pose-oriented & erotic camera work) ──────────────────────
  {
    id: 'dominant_pov',
    label: 'Dominant POV',
    emoji: '👑',
    tag: 'pov, standing, looking down at subject, high angle pov, subject below camera',
    tab: 'intimate',
  },
  {
    id: 'supine_pov',
    label: 'Supine POV',
    emoji: '😌',
    tag: 'pov, lying on back, looking up, subject above camera, low angle pov',
    tab: 'intimate',
  },
  {
    id: 'overhead_lying',
    label: 'Overhead Lying',
    emoji: '🛏️',
    tag: 'overhead shot, top-down view, lying on back, supine pose, full body, rumpled sheets',
    tab: 'intimate',
  },
  {
    id: 'foot_of_bed',
    label: 'Foot of Bed',
    emoji: '🦶',
    tag: 'from foot of bed, low angle, looking toward face, full body in frame, bedroom',
    tab: 'intimate',
  },
  {
    id: 'head_of_bed',
    label: 'Head of Bed',
    emoji: '🧠',
    tag: 'from head of bed, high angle, looking down body, bedroom scene',
    tab: 'intimate',
  },
  {
    id: 'bedside',
    label: 'Bedside View',
    emoji: '🪵',
    tag: 'from bedside, eye level, horizontal subject, side view, bedroom intimate scene',
    tab: 'intimate',
  },
  {
    id: 'ceiling_pov',
    label: 'Ceiling POV',
    emoji: '🔝',
    tag: 'ceiling pov, top-down view, overhead perspective, directly above, wide shot',
    tab: 'intimate',
  },
  {
    id: 'floor_level',
    label: 'Floor Level',
    emoji: '🐜',
    tag: 'floor level camera, from below, worm\'s-eye view, looking up at subject',
    tab: 'intimate',
  },
  {
    id: 'between_legs',
    label: 'Between-Legs Frame',
    emoji: '🔺',
    tag: "shot framed through subject's open legs, between thighs, camera between legs, low angle",
    tab: 'intimate',
  },
  {
    id: 'all_fours_behind',
    label: 'All Fours — Behind',
    emoji: '🐾',
    tag: 'on all fours, from behind, low angle, rear view, eye level',
    tab: 'intimate',
  },
  {
    id: 'all_fours_side',
    label: 'All Fours — Side',
    emoji: '↔️',
    tag: 'on all fours, side view, profile, eye level',
    tab: 'intimate',
  },
  {
    id: 'bent_over_behind',
    label: 'Bent Over — Rear',
    emoji: '🔙',
    tag: 'bent over, from behind, rear view, low angle',
    tab: 'intimate',
  },
  {
    id: 'prone_arch',
    label: 'Prone Arch',
    emoji: '🌙',
    tag: 'prone position, lying on stomach, back arched, overhead shot, three-quarter view',
    tab: 'intimate',
  },
  {
    id: 'arching_profile',
    label: 'Arching — Profile',
    emoji: '🌊',
    tag: 'arching back pose, profile shot, side view, full body, low angle, dramatic silhouette',
    tab: 'intimate',
  },
  {
    id: 'fetal',
    label: 'Fetal / Curled',
    emoji: '🌀',
    tag: 'fetal position, curled up, overhead view, full body, soft light',
    tab: 'intimate',
  },
  {
    id: 'seated_open',
    label: 'Seated — Open',
    emoji: '🪑',
    tag: 'seated, legs open, low camera angle, from front, eye level',
    tab: 'intimate',
  },
  {
    id: 'reaching_up',
    label: 'Reaching Up',
    emoji: '🙌',
    tag: "arms raised overhead, worm's-eye view, from below, looking up, full body, low angle",
    tab: 'intimate',
  },
  {
    id: 'under_sheets',
    label: 'Under Sheets',
    emoji: '🛌',
    tag: 'under sheets, implied nudity, sheet draped across body, slight high angle, boudoir',
    tab: 'intimate',
  },
];
