// Guide Mode — deterministic angle/POV presets with real photographic references & pipeline support
// No LLM involved. Pure delta prompts dispatched sequentially.

export type GuideTab = 'camera' | 'framing' | 'pov' | 'intimate';

export interface GuideAngle {
  id: string;
  label: string;
  emoji: string;
  /** The pure delta prompt string sent to ChatGPT */
  tag: string;
  tab: GuideTab;
  /** Short description of the photographic effect */
  desc: string;
  /** Recommended lens / focal length */
  focalLength: string;
  /** Real photographic reference image preview */
  previewImage: string;
}

export interface GuidePipelineItem {
  id: string; // unique instance ID in pipeline
  angleId: string;
  label: string;
  emoji: string;
  tag: string;
  customPrompt?: string;
  previewImage: string;
  tab: GuideTab;
}

export interface GuideSavedPipeline {
  id: string;
  name: string;
  description?: string;
  itemAngleIds: string[];
}

export const GUIDE_TABS: { id: GuideTab; label: string; emoji: string }[] = [
  { id: 'camera',   label: 'Camera',   emoji: '📷' },
  { id: 'framing',  label: 'Framing',  emoji: '🎞️' },
  { id: 'pov',      label: 'POV',      emoji: '👁️' },
  { id: 'intimate', label: 'Intimate', emoji: '🔥' },
];

export const GUIDE_ANGLES: GuideAngle[] = [
  // ── 📷 Camera (Vertical & Horizontal Angle) ─────────────────────────────
  {
    id: 'eye_level',
    label: 'Eye Level',
    emoji: '👀',
    tag: 'eye level shot, neutral camera height, straight on angle, balanced eye-contact perspective',
    tab: 'camera',
    desc: 'Neutral, natural, direct relation with subject',
    focalLength: '50mm',
    previewImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'low_angle',
    label: 'Low Angle',
    emoji: '📐',
    tag: 'low angle shot, camera placed below looking up at subject, elongated posture, dominant perspective',
    tab: 'camera',
    desc: 'Looking up from below, creates power and lengthens legs',
    focalLength: '28mm',
    previewImage: 'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'slight_low',
    label: 'Slight Low',
    emoji: '⬇️',
    tag: 'slight low angle shot, camera just below eye level, subtle upward perspective, flattering silhouette',
    tab: 'camera',
    desc: 'Subtle flattery, lengthens torso and legs naturally',
    focalLength: '35mm',
    previewImage: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'worms_eye',
    label: "Worm's-Eye / Floor POV",
    emoji: '🐜',
    tag: "worm's-eye view, floor POV, camera on ground looking straight up, dramatic upward perspective, extreme low angle",
    tab: 'camera',
    desc: 'Camera flat on floor looking up, ultra dynamic scale',
    focalLength: '20mm',
    previewImage: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'high_angle',
    label: 'High Angle',
    emoji: '🔭',
    tag: 'high angle shot, looking down at subject, camera placed above, vulnerable delicate framing',
    tab: 'camera',
    desc: 'Camera placed above looking down, intimate and delicate',
    focalLength: '50mm',
    previewImage: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'slight_high',
    label: 'Slight High',
    emoji: '⬆️',
    tag: 'slight high angle shot, camera slightly above eye level looking gently down, soft flattering portrait perspective',
    tab: 'camera',
    desc: 'Soft boudoir favorite, accentuates jawline and eyes',
    focalLength: '85mm',
    previewImage: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'overhead',
    label: 'Overhead / Bird\'s-Eye',
    emoji: '🛸',
    tag: 'overhead shot, top-down view, bird\'s-eye view, camera directly above looking straight down at 90-degree angle',
    tab: 'camera',
    desc: '90-degree angle directly above, graphic and cinematic',
    focalLength: '24mm',
    previewImage: 'https://images.unsplash.com/photo-1516726817505-f5ed825624d8?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'dutch_angle',
    label: 'Dutch / Canted Angle',
    emoji: '↗️',
    tag: 'dutch angle, canted framing, tilted camera horizon, dynamic stylized 45-degree composition',
    tab: 'camera',
    desc: 'Tilted horizon, creates tension and high energy',
    focalLength: '35mm',
    previewImage: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'frontal',
    label: 'Frontal Symmetrical',
    emoji: '⬜',
    tag: 'frontal view, straight on, head-on angle, facing camera directly, perfect symmetrical composition',
    tab: 'camera',
    desc: 'Direct confrontation, perfect Wes Anderson symmetry',
    focalLength: '50mm',
    previewImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'three_quarter',
    label: 'Dynamic 3/4 Profile',
    emoji: '↩️',
    tag: 'dynamic 3/4 profile, three-quarter view of face, head turned slightly, dimensional lighting, flattering angle',
    tab: 'camera',
    desc: 'The gold standard portrait angle with depth & volume',
    focalLength: '85mm',
    previewImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'full_profile',
    label: 'Side Profile',
    emoji: '👤',
    tag: 'full profile shot, strict side view, 90-degree angle, sharp jawline silhouette, clean edge',
    tab: 'camera',
    desc: 'Strict 90-degree side silhouette, highlights facial bone structure',
    focalLength: '85mm',
    previewImage: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'from_behind',
    label: 'From Behind',
    emoji: '🔙',
    tag: 'shot from behind, rear angle, back view, subject facing away from camera, atmospheric depth',
    tab: 'camera',
    desc: 'Subject facing away, mysterious and cinematic',
    focalLength: '50mm',
    previewImage: 'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'looking_back',
    label: 'Looking Back Over Shoulder',
    emoji: '👀',
    tag: 'standing from behind, looking back over shoulder, three-quarter rear view, direct eye contact with camera',
    tab: 'camera',
    desc: 'Rear body with face turned back toward lens',
    focalLength: '85mm',
    previewImage: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=500&auto=format&fit=crop&q=80',
  },

  // ── 🎞️ Framing (Shot Size & Body Crops) ──────────────────────────────────
  {
    id: 'close_up',
    label: 'Close-Up Portrait',
    emoji: '🤳',
    tag: 'close-up portrait headshot, framing head and neck, 85mm lens, sharp focus on eyes, creamy background bokeh',
    tab: 'framing',
    desc: 'Head and shoulders, intimate focus on expression',
    focalLength: '85mm',
    previewImage: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'extreme_close_up',
    label: 'Extreme Close-Up',
    emoji: '🔬',
    tag: 'extreme close-up shot, macro photography, tight crop on eyes and lips, hyper-detailed facial features, razor thin depth of field',
    tab: 'framing',
    desc: 'Macro crop on eyes, lips, or skin texture',
    focalLength: '105mm Macro',
    previewImage: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'bust_shot',
    label: 'Bust Shot (MCU)',
    emoji: '👗',
    tag: 'medium close-up, bust shot, framed from chest up, glamorous portraiture, clean shoulders framing',
    tab: 'framing',
    desc: 'Framed from chest up, glamorous commercial standard',
    focalLength: '85mm',
    previewImage: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'waist_up',
    label: 'Medium Shot (Waist-Up)',
    emoji: '⬛',
    tag: 'medium shot, half-body, framed from waist up, natural conversational framing, body language visible',
    tab: 'framing',
    desc: 'From waist up, balances outfit, pose, and background',
    focalLength: '50mm',
    previewImage: 'https://images.unsplash.com/photo-1524502397800-2eeaad7c3fe5?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'cowboy_shot',
    label: 'Cowboy Shot (Thigh-Up)',
    emoji: '🤠',
    tag: 'cowboy shot, american shot, framed from mid-thigh up, confident stance, framing hips and torso',
    tab: 'framing',
    desc: 'From mid-thigh up, highlights stance and hip silhouette',
    focalLength: '50mm',
    previewImage: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'full_body',
    label: 'Full Body Shot',
    emoji: '🧍',
    tag: 'full body shot, head to toe, wide shot, full character framing, complete standing pose, outfit fully visible',
    tab: 'framing',
    desc: 'Head to toe, fashion and environmental complete capture',
    focalLength: '35mm',
    previewImage: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'torso_crop',
    label: 'Torso Isolation Crop',
    emoji: '✂️',
    tag: 'torso only, no head, no legs, close-up abstract body framing, chest to hip isolation crop, fine art composition',
    tab: 'framing',
    desc: 'Chest through hips isolation, artistic geometry',
    focalLength: '70mm',
    previewImage: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'legs_only',
    label: 'Legs-Only Frame',
    emoji: '🦿',
    tag: 'legs only, thighs to feet, full leg length in frame, low camera angle, footwear and leg silhouette',
    tab: 'framing',
    desc: 'Thighs to feet, highlights legs and stance',
    focalLength: '50mm',
    previewImage: 'https://images.unsplash.com/photo-1516478177764-9fe5bd7e9717?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'silhouette',
    label: 'Backlit Silhouette',
    emoji: '🌅',
    tag: 'silhouette, backlit by bright window, full body, dark subject outline, high contrast, radiant rim lighting',
    tab: 'framing',
    desc: 'Pure dark outline against bright backdrop with rim glow',
    focalLength: '50mm',
    previewImage: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=500&auto=format&fit=crop&q=80',
  },

  // ── 👁️ POV (Point of View & Immersion) ──────────────────────────────────
  {
    id: 'mirror_selfie',
    label: 'Mirror Selfie',
    emoji: '🪞',
    tag: 'mirror selfie, holding smartphone in hand, casual mirror reflection, candid lifestyle angle, full body reflection',
    tab: 'pov',
    desc: 'Holding phone in mirror, modern casual candid',
    focalLength: '24mm Phone',
    previewImage: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'selfie_pov',
    label: 'Selfie Front-Camera POV',
    emoji: '🤳',
    tag: 'selfie angle, handheld pov, arm extended out of frame, taken with smartphone front camera, high intimacy, direct eye contact',
    tab: 'pov',
    desc: 'Arm extended forward, personal front-camera distortion',
    focalLength: '24mm Phone',
    previewImage: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'over_the_shoulder',
    label: 'Over-the-Shoulder (OTS)',
    emoji: '🫧',
    tag: 'over-the-shoulder shot, looking past foreground figure\'s shoulder, shallow depth of field, conversational depth',
    tab: 'pov',
    desc: 'Looking past foreground shoulder, cinematic immersion',
    focalLength: '50mm',
    previewImage: 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'first_person_pov',
    label: 'First-Person POV',
    emoji: '🎮',
    tag: 'first-person POV, shot from viewer\'s perspective, intimate eye-to-eye view, reaching out to camera',
    tab: 'pov',
    desc: 'Viewer is the camera, high intimacy',
    focalLength: '35mm',
    previewImage: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'voyeur_doorway',
    label: 'Doorway Voyeur',
    emoji: '🚪',
    tag: 'framed through doorway, voyeur angle, foreground door frame out of focus, candid subject in room, cinematic depth',
    tab: 'pov',
    desc: 'Framed through open door, unseen observer vibe',
    focalLength: '85mm',
    previewImage: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'voyeur_curtain',
    label: 'Through Sheer Curtain',
    emoji: '🪟',
    tag: 'through sheer curtain, soft foreground fabric blur, voyeuristic perspective, natural window light glowing through cloth',
    tab: 'pov',
    desc: 'Through translucent curtain, dreamy soft blur',
    focalLength: '85mm',
    previewImage: 'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'peephole',
    label: 'Peephole / Fisheye',
    emoji: '🔵',
    tag: 'fisheye lens, peephole perspective, circular vignette distortion, ultra-wide angle, security camera perspective',
    tab: 'pov',
    desc: 'Circular fisheye barrel distortion, surveillance aesthetic',
    focalLength: '8mm Fisheye',
    previewImage: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'self_gaze',
    label: 'Self-Gaze Down Body',
    emoji: '⬇️',
    tag: 'pov, self-gaze, subjective camera looking down at own body, chest-up and lap view from subject\'s own eyes',
    tab: 'pov',
    desc: 'Looking down at own chest and lap, subjective self-view',
    focalLength: '24mm',
    previewImage: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=500&auto=format&fit=crop&q=80',
  },

  // ── 🔥 Intimate (Boudoir, Pose-Driven & Erotica Angles) ───────────────────
  {
    id: 'dominant_standing_pov',
    label: 'Dominant Standing POV',
    emoji: '👑',
    tag: 'pov, standing, looking down at subject, high angle pov, subject seated below camera looking up, dominant viewer perspective',
    tab: 'intimate',
    desc: 'Viewer standing tall looking down at seated/lying subject',
    focalLength: '35mm',
    previewImage: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'supine_upward_pov',
    label: 'Supine Upward POV',
    emoji: '😌',
    tag: 'pov, lying on back, looking up, subject above camera, low angle intimate perspective, close proximity',
    tab: 'intimate',
    desc: 'Viewer lying on back looking up at subject above',
    focalLength: '28mm',
    previewImage: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'overhead_lying',
    label: 'Overhead Lying (Boudoir)',
    emoji: '🛏️',
    tag: 'overhead shot, top-down view, lying on back, supine pose, full body, rumpled white sheets, relaxed intimate posture',
    tab: 'intimate',
    desc: 'Lying on back from directly above, bed linen framing',
    focalLength: '35mm',
    previewImage: 'https://images.unsplash.com/photo-1516726817505-f5ed825624d8?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'foot_of_bed',
    label: 'Foot of Bed Angle',
    emoji: '🦶',
    tag: 'from foot of bed, low angle, looking toward headboard, bedroom scene, full body framed lengthwise across mattress',
    tab: 'intimate',
    desc: 'Camera at footboard looking along body toward headboard',
    focalLength: '35mm',
    previewImage: 'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'head_of_bed',
    label: 'Head of Bed Angle',
    emoji: '🧠',
    tag: 'from head of bed, high angle looking down body toward feet, bedroom intimate scene, pillow framing',
    tab: 'intimate',
    desc: 'Camera behind pillows looking down body toward foot of bed',
    focalLength: '35mm',
    previewImage: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'bedside_eye_level',
    label: 'Bedside Eye-Level',
    emoji: '🪵',
    tag: 'from bedside, horizontal eye level with mattress, side view of lying subject, soft warm lamp light, intimate bedroom',
    tab: 'intimate',
    desc: 'Camera level with mattress surface, side view of lying subject',
    focalLength: '50mm',
    previewImage: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'ceiling_pov',
    label: 'Ceiling POV',
    emoji: '🔝',
    tag: 'ceiling pov, top-down view, overhead perspective, directly above intimate scene, wide environmental framing',
    tab: 'intimate',
    desc: 'Camera mounted on ceiling looking straight down at room',
    focalLength: '20mm',
    previewImage: 'https://images.unsplash.com/photo-1516726817505-f5ed825624d8?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'floor_level_upward',
    label: 'Floor-Level Upward',
    emoji: '🐜',
    tag: 'floor level camera, ground perspective looking up at standing subject, extreme low angle, towering height',
    tab: 'intimate',
    desc: 'Ground-hugging angle looking straight up at standing subject',
    focalLength: '24mm',
    previewImage: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'between_legs_frame',
    label: 'Between-Legs Framing',
    emoji: '🔺',
    tag: 'shot framed through subject\'s open legs, camera placed between knees looking toward torso, low angle composition',
    tab: 'intimate',
    desc: 'Camera framed by subject\'s knees looking up toward torso',
    focalLength: '35mm',
    previewImage: 'https://images.unsplash.com/photo-1516478177764-9fe5bd7e9717?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'all_fours_behind',
    label: 'All Fours — From Behind',
    emoji: '🐾',
    tag: 'on all fours, from behind, low angle rear perspective, small of back arch, eye level with waist',
    tab: 'intimate',
    desc: 'Rear low angle looking forward along arched back',
    focalLength: '50mm',
    previewImage: 'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'all_fours_side',
    label: 'All Fours — Side Profile',
    emoji: '↔️',
    tag: 'on all fours, side view, strict profile framing, eye level with mattress, graceful posture, athletic silhouette',
    tab: 'intimate',
    desc: 'Full side profile on bed or floor, S-curve spine',
    focalLength: '50mm',
    previewImage: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'prone_arch',
    label: 'Prone Arch (On Stomach)',
    emoji: '🌙',
    tag: 'prone position, lying on stomach, back arched upward, overhead three-quarter shot, soft diffused lighting',
    tab: 'intimate',
    desc: 'Lying on stomach with arched upper body and head lifted',
    focalLength: '50mm',
    previewImage: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'arching_profile',
    label: 'Arching Back Profile',
    emoji: '🌊',
    tag: 'arching back pose, profile shot, side view, full body, low angle, dramatic S-curve silhouette, high contrast studio lighting',
    tab: 'intimate',
    desc: 'Extreme S-curve profile, sculpted side lighting',
    focalLength: '85mm',
    previewImage: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'seated_knees_up',
    label: 'Seated Knees Drawn Up',
    emoji: '🪑',
    tag: 'seated pose, knees drawn up to chest, slight high angle from front, arms wrapped around shins, intimate natural posture',
    tab: 'intimate',
    desc: 'Seated with knees up to chest, arms around legs, intimate',
    focalLength: '50mm',
    previewImage: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'under_sheets',
    label: 'Under the Sheets',
    emoji: '🛌',
    tag: 'under sheets, implied nudity, sheet draped delicately across body, slight high angle, morning bedroom sunlight',
    tab: 'intimate',
    desc: 'Fabric draped softly across body, morning window glow',
    focalLength: '50mm',
    previewImage: 'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?w=500&auto=format&fit=crop&q=80',
  },
];

// Pre-made standard multi-shot pipelines users can load in 1 click
export const DEFAULT_PIPELINES: GuideSavedPipeline[] = [
  {
    id: 'preset_essential_4',
    name: '📸 Essential 4-Shot Coverage',
    description: 'The industry-standard portfolio progression: Eye-Level ➔ Dynamic 3/4 ➔ Low Angle ➔ Close-Up Headshot.',
    itemAngleIds: ['eye_level', 'three_quarter', 'low_angle', 'close_up'],
  },
  {
    id: 'preset_candid_social',
    name: '📱 Candid & Social Set',
    description: 'Natural authentic vibe: Selfie POV ➔ Mirror Selfie ➔ Doorway Voyeur ➔ Looking Back.',
    itemAngleIds: ['selfie_pov', 'mirror_selfie', 'voyeur_doorway', 'looking_back'],
  },
  {
    id: 'preset_dramatic_cinematic',
    name: '🎬 Cinematic Drama',
    description: 'High impact film progression: Worm\'s-Eye ➔ Full Body ➔ Dutch Angle ➔ Backlit Silhouette.',
    itemAngleIds: ['worms_eye', 'full_body', 'dutch_angle', 'silhouette'],
  },
  {
    id: 'preset_boudoir_intimate',
    name: '🕯️ Boudoir & Intimate Suite',
    description: 'Intimate bedroom suite: Overhead Lying ➔ Bedside Eye-Level ➔ Foot of Bed ➔ Arching Back Profile.',
    itemAngleIds: ['overhead_lying', 'bedside_eye_level', 'foot_of_bed', 'arching_profile'],
  },
];
